name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run Tests
        run: make model-test

      # Step 5: Auth with Google
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Step 5: Set up Google Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # Step 6: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Step 7: Deploy to Google App Engine
      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --quiet
