name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run Tests
        run: make test

      # Step 5: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Step 6: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Step 7: Deploy to Google App Engine
      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --quiet